{% set name = "nikola" %}
{% set version = "7.8.15" %}
{% set file_ext = "tar.gz" %}
{% set hash_value = "182b4b9254f0d710603ba491853429ad6ef3f955f3e718191336b44cfd649000" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  url: https://files.pythonhosted.org/packages/bf/50/440b6466f328d3b948886d5402ee49baeda575a6f5810a914099c11dd85d/Nikola-7.8.15.tar.gz
  sha256: '{{ hash_value }}'

build:
  number: 0
  entry_points:
    - nikola = nikola.__main__:main
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pygments >=1.6
    - pillow >=2.4.0
    - python-dateutil >=2.6.0
    - docutils >=0.12
    - mako >=1.0.0
    - markdown >=2.4.0
    - unidecode >=0.04.16
    - lxml >=3.3.5
    - yapsy >=1.11.223
    - pyrss2gen >=1.1
    - logbook >=0.7.0
    - blinker >=1.3
    - setuptools >=20.3
    - natsort >=3.5.2
    - requests >=2.2.0
    - piexif >=1.0.3
    - doit >=0.31.0
  run:
    - python
    - pygments >=1.6
    - pillow >=2.4.0
    - python-dateutil >=2.6.0
    - docutils >=0.12
    - mako >=1.0.0
    - markdown >=2.4.0
    - unidecode >=0.04.16
    - lxml >=3.3.5
    - yapsy >=1.11.223
    - pyrss2gen >=1.1
    - logbook >=0.7.0
    - blinker >=1.3
    - setuptools >=20.3
    - natsort >=3.5.2
    - requests >=2.2.0
    - piexif >=1.0.3
    - doit >=0.31.0

test:
  imports:
    - nikola
    - nikola.packages
    - nikola.packages.datecond
    - nikola.packages.tzlocal
    - nikola.plugins
    - nikola.plugins.command
    - nikola.plugins.command.auto
    - nikola.plugins.command.rst2html
    - nikola.plugins.compile
    - nikola.plugins.compile.markdown
    - nikola.plugins.compile.rest
    - nikola.plugins.misc
    - nikola.plugins.task
    - nikola.plugins.task.sitemap
    - nikola.plugins.template
  commands:
    - nikola --help
  requires:
    - pytest

about:
  home: https://getnikola.com/
  license: MIT License
  license_family: MIT
  summary: A modular, fast, simple, static website and blog generator
  description: "Nikola, a Static Site and Blog Generator: in goes content, out comes a website, ready to deploy."

